"""
Core Event System

Provides the foundational event-driven architecture with event bus,
event definitions, and async/sync event handling capabilities.
"""

import asyncio
import logging
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Union
from uuid import uuid4


@dataclass
class Event:
    """
    Base event class for the event-driven system.
    
    All events in the system inherit from this base class to ensure
    consistent structure and metadata tracking.
    """
    event_type: str
    data: Dict[str, Any]
    timestamp: float = field(default_factory=time.time)
    event_id: str = field(default_factory=lambda: str(uuid4()))
    source: Optional[str] = None
    correlation_id: Optional[str] = None
    
    def __post_init__(self):
        """Validate event after initialization."""
        if not self.event_type:
            raise ValueError("Event type cannot be empty")
        if not isinstance(self.data, dict):
            raise TypeError("Event data must be a dictionary")


class EventHandler(ABC):
    """Abstract base class for event handlers."""
    
    @abstractmethod
    async def handle(self, event: Event) -> Optional[Event]:
        """
        Handle an event and optionally return a new event.
        
        Args:
            event: The event to handle
            
        Returns:
            Optional new event to emit
        """
        pass
    
    @property
    @abstractmethod
    def handled_events(self) -> List[str]:
        """List of event types this handler processes."""
        pass


class EventBus:
    """
    Central event bus for managing event publishing and subscription.
    
    Supports both synchronous and asynchronous event handling with
    proper error handling and event correlation.
    """
    
    def __init__(self, logger: Optional[logging.Logger] = None):
        """
        Initialize the event bus.
        
        Args:
            logger: Optional logger instance
        """
        self.logger = logger or logging.getLogger(__name__)
        self._handlers: Dict[str, List[EventHandler]] = {}
        self._sync_handlers: Dict[str, List[Callable]] = {}
        self._middleware: List[Callable] = []
        self._event_history: List[Event] = []
        self._max_history = 1000
        
    def subscribe(self, event_type: str, handler: Union[EventHandler, Callable]):
        """
        Subscribe a handler to an event type.
        
        Args:
            event_type: The type of event to handle
            handler: Event handler (async EventHandler or sync callable)
        """
        if isinstance(handler, EventHandler):
            if event_type not in self._handlers:
                self._handlers[event_type] = []
            self._handlers[event_type].append(handler)
        else:
            # Assume synchronous callable
            if event_type not in self._sync_handlers:
                self._sync_handlers[event_type] = []
            self._sync_handlers[event_type].append(handler)
            
        self.logger.info(f"Subscribed handler to event type: {event_type}")
    
    def add_middleware(self, middleware: Callable[[Event], Event]):
        """
        Add middleware to process events before handlers.
        
        Args:
            middleware: Middleware function that takes and returns an Event
        """
        self._middleware.append(middleware)
    
    async def publish(self, event: Event) -> List[Event]:
        """
        Publish an event to all registered handlers.
        
        Args:
            event: The event to publish
            
        Returns:
            List of events generated by handlers
        """
        self.logger.debug(f"Publishing event: {event.event_type} (ID: {event.event_id})")
        
        # Store event in history
        self._store_event(event)
        
        # Apply middleware
        processed_event = event
        for middleware in self._middleware:
            try:
                processed_event = middleware(processed_event)
            except Exception as e:
                self.logger.error(f"Middleware error: {e}")
                continue
        
        generated_events = []
        
        # Handle async handlers
        if processed_event.event_type in self._handlers:
            handlers = self._handlers[processed_event.event_type]
            
            # Execute handlers concurrently
            tasks = [self._handle_async(handler, processed_event) for handler in handlers]
            results = await asyncio.gather(*tasks, return_exceptions=True)
            
            for result in results:
                if isinstance(result, Exception):
                    self.logger.error(f"Handler error: {result}")
                elif result is not None:
                    generated_events.append(result)
        
        # Handle sync handlers
        if processed_event.event_type in self._sync_handlers:
            handlers = self._sync_handlers[processed_event.event_type]
            
            for handler in handlers:
                try:
                    result = handler(processed_event)
                    if result is not None:
                        generated_events.append(result)
                except Exception as e:
                    self.logger.error(f"Sync handler error: {e}")
        
        return generated_events
    
    async def _handle_async(self, handler: EventHandler, event: Event) -> Optional[Event]:
        """Handle an event with an async handler."""
        try:
            return await handler.handle(event)
        except Exception as e:
            self.logger.error(f"Async handler {handler.__class__.__name__} error: {e}")
            return None
    
    def _store_event(self, event: Event):
        """Store event in history with rotation."""
        self._event_history.append(event)
        if len(self._event_history) > self._max_history:
            self._event_history.pop(0)
    
    def get_event_history(self, event_type: Optional[str] = None, 
                         limit: int = 100) -> List[Event]:
        """
        Get event history optionally filtered by type.
        
        Args:
            event_type: Optional filter by event type
            limit: Maximum number of events to return
            
        Returns:
            List of historical events
        """
        events = self._event_history
        if event_type:
            events = [e for e in events if e.event_type == event_type]
        
        return events[-limit:] if limit else events
    
    def get_stats(self) -> Dict[str, Any]:
        """Get event bus statistics."""
        return {
            'total_handlers': sum(len(handlers) for handlers in self._handlers.values()) +
                            sum(len(handlers) for handlers in self._sync_handlers.values()),
            'async_handler_types': len(self._handlers),
            'sync_handler_types': len(self._sync_handlers), 
            'middleware_count': len(self._middleware),
            'event_history_size': len(self._event_history),
            'handler_details': {
                event_type: len(handlers) for event_type, handlers in {
                    **self._handlers,
                    **self._sync_handlers
                }.items()
            }
        }


# Event type constants
class EventTypes:
    """Constants for standard event types."""
    
    # Audio processing events
    AUDIO_CHUNK_READY = "audio.chunk.ready"
    
    # ASR processing events
    ASR_PROCESS_REQUEST = "asr.process.request"
    TRANSCRIPTION_COMPLETED = "transcription.completed"
    
    # Aggregation events
    TRANSCRIPTION_AGGREGATE = "transcription.aggregate"
    TEXT_READY = "text.ready"
    
    # Error events
    PROCESSING_ERROR = "processing.error"
    
    # System events
    SYSTEM_READY = "system.ready"
    SYSTEM_SHUTDOWN = "system.shutdown"